// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmSo80goNaJ3KC0ZHvDv2EZgOZbnlRYww',
    appId: '1:57711808952:web:82b9c4d4b1481d83a6ff4d',
    messagingSenderId: '57711808952',
    projectId: 'sheild-d4bd4',
    authDomain: 'sheild-d4bd4.firebaseapp.com',
    storageBucket: 'sheild-d4bd4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjLTU0DWp2V2HEBxWJMAtoNAtNAmu7WJs',
    appId: '1:57711808952:android:4e5f6356f0215b80a6ff4d',
    messagingSenderId: '57711808952',
    projectId: 'sheild-d4bd4',
    storageBucket: 'sheild-d4bd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC64Hx648p65KVBLj1CaqBjXwGfnfSzZcQ',
    appId: '1:57711808952:ios:2f8636619adabc26a6ff4d',
    messagingSenderId: '57711808952',
    projectId: 'sheild-d4bd4',
    storageBucket: 'sheild-d4bd4.firebasestorage.app',
    iosBundleId: 'com.example.titleProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC64Hx648p65KVBLj1CaqBjXwGfnfSzZcQ',
    appId: '1:57711808952:ios:2f8636619adabc26a6ff4d',
    messagingSenderId: '57711808952',
    projectId: 'sheild-d4bd4',
    storageBucket: 'sheild-d4bd4.firebasestorage.app',
    iosBundleId: 'com.example.titleProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmSo80goNaJ3KC0ZHvDv2EZgOZbnlRYww',
    appId: '1:57711808952:web:c2ba0401f0419246a6ff4d',
    messagingSenderId: '57711808952',
    projectId: 'sheild-d4bd4',
    authDomain: 'sheild-d4bd4.firebaseapp.com',
    storageBucket: 'sheild-d4bd4.firebasestorage.app',
  );
}